# Generated by Django 2.1.5 on 2019-03-13 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equeue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='service',
            field=models.IntegerField(default=''),
        ),
    ]
