# Generated by Django 2.1.5 on 2019-03-13 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equeue', '0002_person_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='service',
        ),
    ]
