# Generated by Django 2.1.5 on 2019-03-13 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equeue', '0003_remove_person_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='service',
            field=models.IntegerField(default=True),
            preserve_default=False,
        ),
    ]
