# Generated by Django 2.1.5 on 2019-03-14 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('lineNumber', models.IntegerField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=10)),
                ('lastName', models.CharField(max_length=10)),
                ('phoneNumber', models.IntegerField()),
                ('service', models.IntegerField()),
            ],
        ),
    ]
