# Generated by Django 2.1.5 on 2019-03-15 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equeue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='waitTime',
            field=models.IntegerField(default=True),
            preserve_default=False,
        ),
    ]
